config/routes.rb
CallSmith::Application.routes.draw do
  

  resources :contacts do 
    resources :contact_notes
  end
  
  resources :contact_notes

  resources :list_contacts do
    member do
      get :dial
      post:dial
      
      post :handle_dial
      get :handle_dial
    end
  end

  resources :lists do
    resources :list_contacts
    
    member do
      post :connect
      post :next
      post :cancel
      
      post :handle_connect
      get :handle_connect
    end
  end

  resources :calls do
    collection do
      get :start
      post :start
      
      get :next
      
      get :handle
      post :handle
    end
    
    member do
      get :dial
      post:dial
      get :handle
    end
  end

  match 'instructions', :to => 'home#instructions'

  match 'home', :to => 'home#home'
  root :to => "home#home"

  devise_for :users
  resources :users, :only => [:show, :update] do
    member do
      get :bookmarklet
    end
    
    resources :contacts
  end

  

end

app/models/call.rb
class Call < ActiveRecord::Base
  include AASM

  belongs_to :contact
  
  aasm_initial_state :pending

  aasm_state :pending
  aasm_state :queued
  aasm_state :completed


  aasm_event :queue do
    transitions :to => :queued, :from => [:pending]
  end
  
  aasm_event :complete do
    transitions :to => :completed, :from => [:queued]
  end
  
  
  class << self
    include ActionDispatch::Routing::UrlFor
    include Rails.application.routes.url_helpers
    default_url_options[:host] = 'callsmith.heroku.com'
    
    def client
      # put your own credentials here
      account_sid = 'AC480c16e9c9374d60b82894abc39a269e'
      auth_token = '06679fd51c1bddb4643773c77b0d25d3'

      # set up a client to talk to the Twilio REST API
      return Twilio::REST::Client.new account_sid, auth_token
    end
      
    def today
      where(:scheduled_for => Date.today)
    end
      
    def connect user
        Call.client.account.calls.create(
          :from => user.phone_number,
          :to => user.phone_number,
          :url => handle_calls_url(:format => :twiml, :auth_token => user.authentication_token, :callback_type => "start"),
          :StatusCallback  =>  handle_calls_url(:format => :twiml, :auth_token => user.authentication_token, :callback_type => "start_end")
        )
    end  
      
      
    def dial calls
      
    end
    
  end
  
  
  #refrences

  def same_day
    Call.where(:scheduled_for => self.scheduled_for).order("created_at ASC")
  end
  
  def next
    self.same_day.where("created_at > :start_date", {:start_date => self.created_at}).first
  end
  
  def client_call
    Call.client.account.calls.get(self.sid)
  end
  
  
  def redirect
    # redirect an in-progress call
    client_call.redirect_to('http://myapp.com/call-redirect')
  end
  
end

app/controllers/calls_controller.rb
class CallsController < ApplicationController
  before_filter :authenticate_user!
  # GET /calls
  # GET /calls.json
  def index
    @calls = current_user.calls

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @calls }
    end
  end

  def start
    call_gateway = Call.connect(current_user)
    
    flash[:notice] = "Starting calls"
    
    redirect_to root_url
  end


  
  def dial
    @call = Call.find(params[:id])
    @call.complete
    @call.save
    
    render :partial => 'calls/handlers/dial'
  end

  def next
    
    @call = current_user.calls.today.queued.first
    
    # if you have the call sid, you can fetch a call object via:
    call_gateway =  Call.client.account.calls.get(@call.sid)

    # redirect an in-progress call
    call_gateway.redirect_to(dial_call_url(@call, :format => :twiml, :auth_token => current_user.authentication_token))
    
    flash[:notice] = "Starting Next Call"
    redirect_to root_url
  end
  
  

  # GET /calls/1
  # GET /calls/1.json
  def show
    @call = Call.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @call }
      format.twiml {  }
    end
  end
  
  

 def handle 
    logger.info "Callback Type: " + params[:callback_type]
    
    if params[:callback_type] == "start"
      if current_user.calls.today.pending.count > 0
        
        current_user.calls.today.pending.each{|call|
          call.queue
          call.save
        }
        
        current_user.calls.today.queued.each{|call|
          logger.info "Setting Call Sid: " + params[:CallSid]
          call.sid = params[:CallSid]
          call.save
        }
        
    	  render :partial => 'calls/handlers/start'
      else
        render :partial => 'calls/handlers/empty_queue'
      end
    elsif params[:callback_type] == "start_end"
      render :partial => 'calls/handlers/start_end'
    end
    
 end
 
   def status_callback
   
   end


  # GET /calls/new
  # GET /calls/new.json
  def new
    @call = Call.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @call }
    end
  end

  # GET /calls/1/edit
  def edit
    @call = Call.find(params[:id])
  end

  # POST /calls
  # POST /calls.json
  def create
    @call = Call.new(params[:call])

    respond_to do |format|
      if @call.save
        format.html { redirect_to root_url, notice: 'Call was successfully created.' }
        format.json { render json: @call, status: :created, location: @call }
      else
        format.html { render action: "new" }
        format.json { render json: @call.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /calls/1
  # PUT /calls/1.json
  def update
    @call = Call.find(params[:id])

    respond_to do |format|
      if @call.update_attributes(params[:call])
        format.html { redirect_to @call, notice: 'Call was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @call.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /calls/1
  # DELETE /calls/1.json
  def destroy
    @call = Call.find(params[:id])
    @call.destroy

    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :ok }
    end
  end
end

app/helpers/calls_helper.rb
module CallsHelper
end

app/views/calls/_form.html.erb
<%= semantic_form_for @call do |f| %>
    
 	<%= f.inputs do %>
    	<%= f.input :contact_id, :as => :select,  :collection => current_user.contacts.map{|contact| ["#{contact.first_name} #{contact.last_name}", contact.id]}%>
		<%= f.input :scheduled_for, :as => :datepicker%>
	<% end %>
    <%= f.buttons %>
  <% end %>

app/views/calls/edit.html.erb
<h1>Editing call</h1>

<%= render 'form' %>

<%= link_to 'Show', @call %> |
<%= link_to 'Back', calls_path %>

app/views/calls/index.html.erb
<h1>Listing calls</h1>

<table class="nice">
  <tr>
    <td>Phone Number</td>
    <td>Scheduled for</td>
    <td colspan=3>Actions</td>
  </tr>

<% @calls.each do |call| %>
  <tr>
    <td><%= call.contact.phone_number %></td>
    <td><%= call.scheduled_for %></td>
    <td><%= link_to 'Show', call %></td>
    <td><%= link_to 'Edit', edit_call_path(call) %></td>
    <td><%= link_to 'Destroy', call, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Call', new_call_path %>

app/views/calls/new.html.erb
<h1>New call</h1>

<%= render 'form' %>

<%= link_to 'Back', calls_path %>

app/views/calls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Contact:</b>
  <%= @call.contact_id %>
</p>

<p>
  <b>Scheduled for:</b>
  <%= @call.scheduled_for %>
</p>

<%= link_to 'Edit', edit_call_path(@call) %> |
<%= link_to 'Back', calls_path %>

app/views/calls/start.twiml.erb
<?xml version="1.0" encoding="UTF-8"?>
<Response>
	<Say voice="woman">
		Calling  <%= @calls.count %> number.
	</Say>
	
	<Dial action="<%= call_url(@calls.first, :format => :twiml, :auth_token => current_user.authentication_token, :callback_type => "start")%>" method="GET">
  		<%= @call.contact.phone_number %>
	</Dial>
</Response>