config/routes.rb
CallSmith::Application.routes.draw do
  

  resources :contacts do 
    resources :contact_notes
  end
  
  resources :contact_notes

  resources :list_contacts do
    member do
      get :dial
      post:dial
      
      post :handle_dial
      get :handle_dial
    end
  end

  resources :lists do
    resources :list_contacts
    
    member do
      post :connect
      post :next
      post :cancel
      
      post :handle_connect
      get :handle_connect
    end
  end

  resources :calls do
    collection do
      get :start
      post :start
      
      get :next
      
      get :handle
      post :handle
    end
    
    member do
      get :dial
      post:dial
      get :handle
    end
  end

  match 'instructions', :to => 'home#instructions'

  match 'home', :to => 'home#home'
  root :to => "home#home"

  devise_for :users
  resources :users, :only => [:show, :update] do
    member do
      get :bookmarklet
    end
    
    resources :contacts
  end

  

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!, :except => [:index]
  
  def index
    @users = User.all
    
    render :layout => 'application'
  end
  
  def home
  end
  
  def instructions
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/home.html.erb
<div id="CallSmithApp"></div>

<script type="text/javascript">
  $(function() {
	window.AppInstance = new CallSmith.Views.ApplicationView({lists: <%= current_user.lists.to_json.html_safe %> <%= current_user.lists.today.first ? ", currentListId: #{current_user.lists.today.first.id}" : "" %>});
  });
</script>

app/views/home/index.html.erb
<% if user_signed_in? %>

<div class="eight columns alpha">
	<CENTER><%= link_to 'Start',start_calls_path, confirm: 'Are you sure?', :class => "button" %> <%= link_to 'Next', next_calls_path, confirm: 'Are you sure?', :class => "button" %></CENTER>
</div>
<div class="clear"></div>
<div class="eight columns alpha">
<table class="nice">
  <tr>
    <td width=15%>Status</td>
    <td width=40%>Name</td>
    <td width=35%>Phone Number</td>
    <td width=10% colspan=2>Actions</td>
  </tr>

<% current_user.calls.pending.each do |call| %>
<div class="callitem">
  <tr>
    <td><%= call.aasm_state %></td>
    <td><%= call.contact.first_name %></td>
	<td><%= call.contact.phone_number %></td>    
<td><%= link_to image_tag("call.png", :size => "25x25"), dial_call_path(call), confirm: 'Are you sure?' %></td>
    <td><%= link_to image_tag("destroy.png", :size => "25x25"), call, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
</div>
<% end %>
</table>
</div>

<div class="eight columns omega">
<table class="side">
		<tr>
			<td>Notes</td>
		</tr>
		<TR><TD>blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah </TD></TR>
</table>
</div>
<div class="clear"></div>
<BR>
<%@call = Call.new%>
<% else %>
<CENTER><H1>CallSmith</h1>
		<%= link_to('Sign up', new_user_registration_path, :class => 'button')  %>
		<%= link_to('Login', new_user_session_path, :class => 'button')  %>  
</CENTER>
<% end %>

app/views/home/instructions.html.erb
<BR><BR>
<h4>Installation Instructions</h4>
<div class="ten columns alpha">
<div class="instructions">
	<a href="javascript:(function(){
		insert_script=document.createElement('SCRIPT');
		insert_script.type='text/javascript';
		insert_script.src='<%=bookmarklet_user_url(current_user, :format => :js, :auth_token => current_user.authentication_token)%>';
		document.getElementsByTagName('head')[0].appendChild(insert_script);
		})();" onclick="alert('Drag me to the bookmark bar!')" class="myButton">CallSmith</a> ← Drag this into your bookmark bar
</div>

<p>If you don't see a bookmark bar, turn it on by clicking the Wrench icon (Preferences). The option is under Basics > Toolbar.<BR></p>
<p><B>Grab numbers!</B> Click your new CallSmith button to grab this number: 555-123-4567. Hit "Save" to add it to your call list.</p>
<p><B>Start Callin'!</B> Go to your <span class="label success"><%= link_to("Call List", root_url)%></span> and click the "Start" button!
</div>
<div class="six columns omega"><%= image_tag("instructions.png")%></div>




<div class="clear"></Div>