config/routes.rb
CallSmith::Application.routes.draw do
  

  resources :contacts do 
    resources :contact_notes
  end
  
  resources :contact_notes

  resources :list_contacts do
    member do
      get :dial
      post:dial
      
      post :handle_dial
      get :handle_dial
    end
  end

  resources :lists do
    resources :list_contacts
    
    member do
      post :connect
      post :next
      post :cancel
      
      post :handle_connect
      get :handle_connect
    end
  end

  resources :calls do
    collection do
      get :start
      post :start
      
      get :next
      
      get :handle
      post :handle
    end
    
    member do
      get :dial
      post:dial
      get :handle
    end
  end

  match 'instructions', :to => 'home#instructions'

  match 'home', :to => 'home#home'
  root :to => "home#home"

  devise_for :users
  resources :users, :only => [:show, :update] do
    member do
      get :bookmarklet
    end
    
    resources :contacts
  end

  

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :user
  
  has_many :calls, :dependent => :destroy
  has_many :contact_notes, :dependent => :destroy
  has_many :list_contacts, :dependent => :destroy

  has_many :lists, :through => :list_contacts
    
  accepts_nested_attributes_for :calls
  
  class << self
    public  
      def phone_regex
        "/[01]?[- .]?\\(?[2-9]\\d{2}\\)?[- .]?\\d{3}[- .]?\\d{4}/"
      end  
  end
  
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_filter :authenticate_user!
  
  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = current_user.contacts.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @contacts }
    end
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
    @contact = Contact.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @contact }
    end
  end

  # GET /contacts/new
  # GET /contacts/new.json
  def new
    @contact = Contact.new(:phone_number => params[:phone_number])
    
    if request.xhr?
      respond_to do |format|
        format.html { render partial: 'new' }
        format.json { render json: @contact }
      end
    else
      respond_to do |format|
        format.html
        format.json { render json: @contact }
      end
    end
  end

  # GET /contacts/1/edit
  def edit
    @contact = Contact.find(params[:id])
  end

  # POST /contacts
  # POST /contacts.json
  def create
    
    #TODO Rails needs to improve this -Joseph
    scheduled_for = Date.civil(params[:scheduled_for][:"scheduled_for(1i)"].to_i,params[:scheduled_for][:"scheduled_for(2i)"].to_i,params[:scheduled_for][:"scheduled_for(3i)"].to_i)
    
    @list = current_user.lists.find_or_create_by_scheduled_for(scheduled_for)
    
    @contact = current_user.contacts.new(params[:contact])
    @list.contacts << @contact
    
    if request.xhr?
      if @contact.save && @list.save
        respond_to do |format|
          format.html { render partial: 'new' }
          format.json { render json: @contact }
        end
      end
    else
      respond_to do |format|
        if @contact.save
          format.html { redirect_to [current_user, @contact], notice: 'Contact was successfully created.' }
          format.json { render json: @contact, status: :created, location: @contact }
        else
          format.html { render action: "new" }
          format.json { render json: @contact.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PUT /contacts/1
  # PUT /contacts/1.json
  def update
    @contact = Contact.find(params[:id])

    respond_to do |format|
      if @contact.update_attributes(params[:contact])
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy

    respond_to do |format|
      format.html { redirect_to user_contacts_url }
      format.json { head :ok }
    end
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<%
@contact.calls.build(:scheduled_for => Date.today)
%>


<%= semantic_form_for [current_user, @contact] do |form| %>

	<% @contact.calls.each do |call| %>
		<%= form.semantic_fields_for :calls do |call| %>
	    	<%= call.input :scheduled_for %>
		<% end %>
	<% end %>

  	<%= form.input :phone_number, :as => :hidden, :label => false %>
	<%= form.input :first_name %>
	<%= form.input :last_name %>
	
	 <%= form.buttons %>
<% end %>

app/views/contacts/_new.html.erb
<%
@contact.calls.build(:scheduled_for => Date.today)
%>

<%= semantic_form_for [current_user, @contact], :url => user_contacts_url(:auth_token => current_user.authentication_token), :remote => true do |form| %>

	<% @contact.calls.each do |call| %>
		<%= form.semantic_fields_for :calls do |call| %>
	    	<%= call.input :scheduled_for, :label => false  %>
		<% end %>
	<% end %>
	<div class='content-controls'>

  	<%= form.input :phone_number, :as => :hidden, :label => false %>
	<%= form.input :first_name, :label => false, :input_html => { :placeholder => "First Name" }  %>
	<%= form.input :last_name, :label => false, :input_html => { :placeholder => "Last Name" }   %>
	</div>
	 <%= form.buttons %>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<h1>Listing contacts</h1>

<table class="nice">
  <tr>
    <td>Phone Number</td>
    <td>First name</td>
    <td>Last name</td>
    <td>Company</td>
    <td>Source</td>
    <td colspan=3>Actions</td>
  </tr>

<% @contacts.each do |contact| %>
  <tr>
    <td><%= contact.phone_number %></td>
    <td><%= contact.first_name %></td>
    <td><%= contact.last_name %></td>
    <td><%= contact.company %></td>
    <td><%= contact.source %></td>
    <td><%= link_to 'Show', [current_user, contact] %></td>
    <td><%= link_to 'Edit', edit_user_contact_path(current_user, contact) %></td>
    <td><%= link_to 'Destroy', [current_user, contact], confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Contact', new_user_contact_path %>

app/views/contacts/new.html.erb
<h1>New contact</h1>

<%= render 'form' %>

<%= link_to 'Back', user_contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @contact.user_id %>
</p>

<p>
  <b>Phone Number:</b>
  <%= @contact.phone_number %>
</p>

<p>
  <b>First name:</b>
  <%= @contact.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @contact.last_name %>
</p>

<p>
  <b>Company:</b>
  <%= @contact.company %>
</p>

<p>
  <b>Source:</b>
  <%= @contact.source %>
</p>


<%= link_to 'Edit', edit_user_contact_path(current_user, @contact) %> |
<%= link_to 'Back', user_contacts_path(current_user) %>