config/routes.rb
CallSmith::Application.routes.draw do
  

  resources :contacts do 
    resources :contact_notes
  end
  
  resources :contact_notes

  resources :list_contacts do
    member do
      get :dial
      post:dial
      
      post :handle_dial
      get :handle_dial
    end
  end

  resources :lists do
    resources :list_contacts
    
    member do
      post :connect
      post :next
      post :cancel
      
      post :handle_connect
      get :handle_connect
    end
  end

  resources :calls do
    collection do
      get :start
      post :start
      
      get :next
      
      get :handle
      post :handle
    end
    
    member do
      get :dial
      post:dial
      get :handle
    end
  end

  match 'instructions', :to => 'home#instructions'

  match 'home', :to => 'home#home'
  root :to => "home#home"

  devise_for :users
  resources :users, :only => [:show, :update] do
    member do
      get :bookmarklet
    end
    
    resources :contacts
  end

  

end

app/models/contact_note.rb
class ContactNote < ActiveRecord::Base
  belongs_to :contact  
end

app/controllers/contact_notes_controller.rb
class ContactNotesController < ApplicationController
  before_filter :authenticate_user!
  
  # GET /contact_notes
  # GET /contact_notes.json
  def index
    @contact_notes = current_user.contacts.find(params[:contact_id]).contact_notes

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @contact_notes }
    end
  end

  # GET /contact_notes/1
  # GET /contact_notes/1.json
  def show
    @contact_note = current_user.contacts.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @contact_note }
    end
  end

  # GET /contact_notes/new
  # GET /contact_notes/new.json
  def new
    @contact_note = current_user.contacts.find(params[:contact_id]).contact_notes.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @contact_note }
    end
  end

  # GET /contact_notes/1/edit
  def edit
    @contact_note = current_user.contacts.find(params[:id])
  end

  # POST /contact_notes
  # POST /contact_notes.json
  def create
    @contact_note = current_user.contacts.find(params[:contact_id]).contact_notes.new(params[:contact_note])

    respond_to do |format|
      if @contact_note.save
        format.html { redirect_to @contact_note, notice: 'Contact note was successfully created.' }
        format.json { render json: @contact_note, status: :created, location: @contact_note }
      else
        format.html { render action: "new" }
        format.json { render json: @contact_note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /contact_notes/1
  # PUT /contact_notes/1.json
  def update
    @contact_note = current_user.contacts.find(params[:id])

    respond_to do |format|
      if @contact_note.update_attributes(params[:contact_note])
        format.html { redirect_to @contact_note, notice: 'Contact note was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @contact_note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contact_notes/1
  # DELETE /contact_notes/1.json
  def destroy
    @contact_note = current_user.contacts.find(params[:id])
    @contact_note.destroy

    respond_to do |format|
      format.html { redirect_to contact_notes_url }
      format.json { head :ok }
    end
  end
end

app/helpers/contact_notes_helper.rb
module ContactNotesHelper
end

app/views/contact_notes/_form.html.erb
<%= form_for(@contact_note) do |f| %>
  <% if @contact_note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact_note.errors.count, "error") %> prohibited this contact_note from being saved:</h2>

      <ul>
      <% @contact_note.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :contact_id %><br />
    <%= f.number_field :contact_id %>
  </div>
  <div class="field">
    <%= f.label :text %><br />
    <%= f.text_area :text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contact_notes/edit.html.erb
<h1>Editing contact_note</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact_note %> |
<%= link_to 'Back', contact_notes_path %>

app/views/contact_notes/index.html.erb
<h1>Listing contact_notes</h1>

<table>
  <tr>
    <th>Contact</th>
    <th>Text</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @contact_notes.each do |contact_note| %>
  <tr>
    <td><%= contact_note.contact_id %></td>
    <td><%= contact_note.text %></td>
    <td><%= link_to 'Show', contact_note %></td>
    <td><%= link_to 'Edit', edit_contact_note_path(contact_note) %></td>
    <td><%= link_to 'Destroy', contact_note, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Contact note', new_contact_note_path %>

app/views/contact_notes/new.html.erb
<h1>New contact_note</h1>

<%= render 'form' %>

<%= link_to 'Back', contact_notes_path %>

app/views/contact_notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Contact:</b>
  <%= @contact_note.contact_id %>
</p>

<p>
  <b>Text:</b>
  <%= @contact_note.text %>
</p>


<%= link_to 'Edit', edit_contact_note_path(@contact_note) %> |
<%= link_to 'Back', contact_notes_path %>